#pragma once

// =============================================================================
// GENERATED SAVED-CONFIG SWITCH HELPERS - do not edit by hand
// Generated by scripts/build.py from common/config/card_contract.json.
// =============================================================================

template<typename Config, typename OptionHook>
inline bool normalize_saved_config_switch(Config &config,
                                         OptionHook normalize_options) {
  if (!config.type.empty()) return false;
    config.type = "";
  config.options = normalize_options(config.options);
  return true;
}
