#pragma once

// =============================================================================
// GENERATED SAVED-CONFIG ACTION HELPERS - do not edit by hand
// Generated by scripts/build.py from common/config/card_contract.json.
// =============================================================================

template<typename Config>
inline bool migrate_saved_config_action_legacy(Config &config) {
  if (config.type == "local") {
    config.type = "action";
    config.sensor = "local";
    config.unit.clear();
    config.precision.clear();
    config.options.clear();
    config.icon_on = "Auto";
    return true;
  }
  if (config.type == "option_select") {
    config.type = "action";
    config.sensor = "input_select.select_option";
    config.unit.clear();
    config.precision.clear();
    config.options.clear();
    config.icon_on = "Auto";
    return true;
  }
  return false;
}
