// =============================================================================
// ICONS - MDI icon lookup table and HA entity state helpers
// =============================================================================
// Maps human-readable icon names (e.g. "Lightbulb") to MDI Unicode codepoints
// for LVGL label rendering. The ICON_ENTRIES table and domain_default_icon()
// chain are partially generated by scripts/build.py from icons.json.
// =============================================================================
#pragma once

#include <cstring>
#include <cstddef>

struct IconEntry {
  const char* name;   // display name used in web UI icon picker
  const char* glyph;  // UTF-8 encoded MDI codepoint for LVGL
};

static const IconEntry ICON_ENTRIES[] = {
    // --- GENERATED:ICONS START ---
    {"Account",                    "\U000F0004"},
    {"Air Conditioner",            "\U000F001B"},
    {"Air Filter",                 "\U000F0D43"},
    {"Air Purifier",               "\U000F0D44"},
    {"Alarm",                      "\U000F009E"},
    {"Alarm Light",                "\U000F078F"},
    {"Application",                "\U000F0614"},
    {"Battery",                    "\U000F0079"},
    {"Battery 10%",                "\U000F007A"},
    {"Battery 20%",                "\U000F007B"},
    {"Battery 30%",                "\U000F007C"},
    {"Battery 40%",                "\U000F007D"},
    {"Battery 50%",                "\U000F007E"},
    {"Battery 60%",                "\U000F007F"},
    {"Battery 70%",                "\U000F0080"},
    {"Battery 80%",                "\U000F0081"},
    {"Battery 90%",                "\U000F0082"},
    {"Battery Alert",              "\U000F0083"},
    {"Battery Charging",           "\U000F0084"},
    {"Battery Charging 100",       "\U000F0085"},
    {"Battery Charging 70",        "\U000F089E"},
    {"Battery High",               "\U000F12A3"},
    {"Battery Low",                "\U000F12A1"},
    {"Battery Medium",             "\U000F12A2"},
    {"Battery Off",                "\U000F125D"},
    {"Battery Outline",            "\U000F008E"},
    {"Battery Unknown",            "\U000F0091"},
    {"Bed",                        "\U000F02E3"},
    {"Bell",                       "\U000F009A"},
    {"Blinds",                     "\U000F00AC"},
    {"Blinds Horizontal",          "\U000F1A2B"},
    {"Blinds Horizontal Closed",   "\U000F1A2C"},
    {"Blinds Open",                "\U000F1011"},
    {"Bluetooth",                  "\U000F00AF"},
    {"Broom",                      "\U000F00E2"},
    {"Camera",                     "\U000F0100"},
    {"Car Electric",               "\U000F0B6C"},
    {"Cast",                       "\U000F0118"},
    {"CCTV",                       "\U000F07AE"},
    {"Ceiling Fan",                "\U000F1797"},
    {"Ceiling Light",              "\U000F0769"},
    {"Chandelier",                 "\U000F1793"},
    {"Clock",                      "\U000F0150"},
    {"Coffee Maker",               "\U000F109F"},
    {"Current AC",                 "\U000F1480"},
    {"Current DC",                 "\U000F095C"},
    {"Curtains",                   "\U000F1846"},
    {"Curtains Closed",            "\U000F1847"},
    {"Desk Lamp",                  "\U000F095F"},
    {"Dishwasher",                 "\U000F0AAC"},
    {"Dog",                        "\U000F0A43"},
    {"Downlight",                  "\U000F179B"},
    {"Door",                       "\U000F081A"},
    {"Door Open",                  "\U000F081C"},
    {"Doorbell",                   "\U000F0869"},
    {"Dryer",                      "\U000F0917"},
    {"EV Charger",                 "\U000F05F1"},
    {"Fan",                        "\U000F0210"},
    {"Fire",                       "\U000F0238"},
    {"Fireplace",                  "\U000F0E2E"},
    {"Flash",                      "\U000F0241"},
    {"Floor Lamp",                 "\U000F08DD"},
    {"Fountain",                   "\U000F096B"},
    {"Fridge",                     "\U000F0290"},
    {"Gamepad",                    "\U000F0297"},
    {"Garage",                     "\U000F06D9"},
    {"Garage Open",                "\U000F06DA"},
    {"Garage Open Variant",        "\U000F12D4"},
    {"Garage Variant",             "\U000F12D3"},
    {"Gate",                       "\U000F0299"},
    {"Gate Open",                  "\U000F116A"},
    {"Gesture Tap",                "\U000F0741"},
    {"Gauge",                      "\U000F029A"},
    {"Gauge Empty",                "\U000F0873"},
    {"Gauge Full",                 "\U000F0874"},
    {"Gauge Low",                  "\U000F0875"},
    {"Grid Export",                "\U000F192C"},
    {"Grid Import",                "\U000F192D"},
    {"Grid Off",                   "\U000F19DD"},
    {"Headphones",                 "\U000F02CB"},
    {"Heater",                     "\U000F0438"},
    {"Home",                       "\U000F02DC"},
    {"Hot Tub",                    "\U000F0828"},
    {"Humidifier",                 "\U000F1099"},
    {"Humidity Alert",             "\U000F1509"},
    {"Iron",                       "\U000F1824"},
    {"Kettle",                     "\U000F05FA"},
    {"Key",                        "\U000F030B"},
    {"Lamp",                       "\U000F06B5"},
    {"Lamp Outline",               "\U000F17D0"},
    {"LAN",                        "\U000F0317"},
    {"Lawnmower",                  "\U000F11F7"},
    {"Leaf",                       "\U000F032A"},
    {"LED Strip",                  "\U000F07D6"},
    {"LED Strip Variant",          "\U000F1051"},
    {"LED Strip Variant Off",      "\U000F1A4B"},
    {"Light Switch",               "\U000F097E"},
    {"Lightbulb",                  "\U000F0335"},
    {"Lightbulb Group",            "\U000F1253"},
    {"Lightbulb Group Outline",    "\U000F1254"},
    {"Lightbulb Night",            "\U000F1A4C"},
    {"Lightbulb Night Outline",    "\U000F1A4D"},
    {"Lightbulb Off",              "\U000F0E4F"},
    {"Lightbulb On Outline",       "\U000F06E9"},
    {"Lightbulb Spot",             "\U000F17F4"},
    {"Lightbulb Spot Off",         "\U000F17F5"},
    {"Lightbulb Variant",          "\U000F1802"},
    {"Lightbulb Variant Outline",  "\U000F1803"},
    {"Lightbulb Outline",          "\U000F0336"},
    {"Lightning Bolt",             "\U000F140B"},
    {"Lock",                       "\U000F033E"},
    {"Lock Open",                  "\U000F033F"},
    {"Lock Open Outline",          "\U000F0340"},
    {"Lock Outline",               "\U000F0341"},
    {"Mailbox",                    "\U000F06EE"},
    {"Message Video",              "\U000F036B"},
    {"Medication",                 "\U000F1B14"},
    {"Medication Outline",         "\U000F1B15"},
    {"Meter Electric",             "\U000F1A57"},
    {"Meter Gas",                  "\U000F1A59"},
    {"Microsoft Xbox",             "\U000F05B9"},
    {"Microwave",                  "\U000F0C99"},
    {"Monitor",                    "\U000F0379"},
    {"Motion Sensor",              "\U000F0D91"},
    {"Movie Roll",                 "\U000F07DE"},
    {"Music",                      "\U000F075A"},
    {"Outdoor Lamp",               "\U000F1054"},
    {"Oven",                       "\U000F04DE"},
    {"Package",                    "\U000F03D6"},
    {"Package Closed",             "\U000F03D7"},
    {"Pill",                       "\U000F0402"},
    {"Pill Multiple",              "\U000F1B4C"},
    {"Pool",                       "\U000F0606"},
    {"Power",                      "\U000F0425"},
    {"Power Plug",                 "\U000F06A5"},
    {"Printer",                    "\U000F042A"},
    {"Printer 3D",                 "\U000F042B"},
    {"Projector",                  "\U000F042E"},
    {"Projector Off",              "\U000F1A23"},
    {"Robot Vacuum",               "\U000F070D"},
    {"Roller Shade",               "\U000F1A6B"},
    {"Roller Shade Closed",        "\U000F1A6C"},
    {"Router",                     "\U000F0469"},
    {"Router Network",             "\U000F1087"},
    {"Security",                   "\U000F068A"},
    {"Shower",                     "\U000F09A1"},
    {"Smoke Detector",             "\U000F0392"},
    {"Snowflake",                  "\U000F0717"},
    {"Snowflake Alert",            "\U000F0F29"},
    {"Snowflake Thermometer",      "\U000F1A71"},
    {"Sofa",                       "\U000F04B9"},
    {"Solar Panel",                "\U000F0D9B"},
    {"Solar Panel Large",          "\U000F0D9C"},
    {"Solar Power",                "\U000F0A72"},
    {"Solar Power Variant",        "\U000F1A73"},
    {"Speaker",                    "\U000F04C3"},
    {"Spotlight",                  "\U000F04C9"},
    {"Sprinkler",                  "\U000F105F"},
    {"String Lights",              "\U000F12BA"},
    {"String Lights Off",          "\U000F12BB"},
    {"Sun",                        "\U000F05A8"},
    {"Table",                      "\U000F05BC"},
    {"Television",                 "\U000F0502"},
    {"Television Off",             "\U000F083B"},
    {"Thermometer",                "\U000F050F"},
    {"Thermometer Alert",          "\U000F0E01"},
    {"Thermometer High",           "\U000F10C2"},
    {"Thermometer Low",            "\U000F10C3"},
    {"Thermostat",                 "\U000F0393"},
    {"Timer",                      "\U000F051B"},
    {"Toilet",                     "\U000F09AB"},
    {"Transmission Tower",         "\U000F0D3E"},
    {"Trash Can",                  "\U000F0A79"},
    {"Wall Outlet",                "\U000F0427"},
    {"Wall Sconce",                "\U000F091C"},
    {"Washer",                     "\U000F072A"},
    {"Water",                      "\U000F058C"},
    {"Water Heater",               "\U000F0F92"},
    {"Water Percent",              "\U000F058E"},
    {"Weather Cloudy",             "\U000F0590"},
    {"Weather Cloudy Alert",       "\U000F0F2F"},
    {"Weather Dust",               "\U000F1B5A"},
    {"Weather Fog",                "\U000F0591"},
    {"Weather Hail",               "\U000F0592"},
    {"Weather Hazy",               "\U000F0F30"},
    {"Weather Hurricane",          "\U000F0898"},
    {"Weather Lightning",          "\U000F0593"},
    {"Weather Lightning Rainy",    "\U000F067E"},
    {"Weather Night",              "\U000F0594"},
    {"Weather Night Cloudy",       "\U000F0F31"},
    {"Weather Partly Cloudy",      "\U000F0595"},
    {"Weather Partly Lightning",   "\U000F0F32"},
    {"Weather Partly Rainy",       "\U000F0F33"},
    {"Weather Partly Snowy",       "\U000F0F34"},
    {"Weather Partly Snowy Rainy", "\U000F0F35"},
    {"Weather Pouring",            "\U000F0596"},
    {"Weather Rainy",              "\U000F0597"},
    {"Weather Snowy",              "\U000F0598"},
    {"Weather Snowy Heavy",        "\U000F0F36"},
    {"Weather Snowy Rainy",        "\U000F067F"},
    {"Weather Sunny",              "\U000F0599"},
    {"Weather Sunny Alert",        "\U000F0F37"},
    {"Weather Sunny Off",          "\U000F14E4"},
    {"Weather Sunset",             "\U000F059A"},
    {"Weather Sunset Down",        "\U000F059B"},
    {"Weather Sunset Up",          "\U000F059C"},
    {"Weather Tornado",            "\U000F0F38"},
    {"Weather Windy",              "\U000F059D"},
    {"Weather Windy Variant",      "\U000F059E"},
    {"Wind Power",                 "\U000F1A88"},
    {"Wind Turbine",               "\U000F0DA5"},
    {"Wind Turbine Alert",         "\U000F19AB"},
    {"Wind Turbine Check",         "\U000F19AC"},
    {"Window Shutter",             "\U000F111C"},
    {"Window Shutter Open",        "\U000F111E"},
    // --- GENERATED:ICONS END ---
};

static constexpr size_t NUM_ICONS = sizeof(ICON_ENTRIES) / sizeof(ICON_ENTRIES[0]);

// Linear search for an icon name; returns fallback (cog) if not found
inline const char* find_icon(const char* name) {
  for (size_t i = 0; i < NUM_ICONS; i++) {
    if (std::strcmp(ICON_ENTRIES[i].name, name) == 0) {
      return ICON_ENTRIES[i].glyph;
    }
  }
  return "\U000F0493";
}

// Return the default icon for a HA entity domain (e.g. "light" → Lightbulb)
inline const char* domain_default_icon(const std::string &domain) {
  // --- GENERATED:DOMAIN_ICONS START ---
  if (domain == "light")                      return "\U000F0335";  // Lightbulb
  if (domain == "switch")                     return "\U000F06A5";  // Power Plug
  if (domain == "fan")                        return "\U000F0210";  // Fan
  if (domain == "lock")                       return "\U000F033E";  // Lock
  if (domain == "cover")                      return "\U000F1A2B";  // Blinds Horizontal
  if (domain == "climate")                    return "\U000F001B";  // Air Conditioner
  if (domain == "media_player")               return "\U000F04C3";  // Speaker
  if (domain == "camera")                     return "\U000F0100";  // Camera
  if (domain == "button")                     return "\U000F0741";  // Gesture Tap
  if (domain == "binary_sensor")              return "\U000F0D91";  // Motion Sensor
  // --- GENERATED:DOMAIN_ICONS END ---
  return "\U000F0493";
}

// Check if a HA entity state string represents "on" (covers, locks, media, etc.)
inline bool is_entity_on(const std::string &state) {
  return state == "on" ||
         state == "open" ||
         state == "opening" ||
         state == "closing" ||
         state == "playing" ||
         state == "home" ||
         state == "unlocked";
}
