substitutions:
  name: "espcontrol-jc1060p470"
  friendly_name: "Espcontrol 7inch"

esphome:
  name_add_mac_suffix: true

packages:
  espcontrol: !include ../devices/guition-esp32-p4-jc1060p470/packages.yaml

wifi:
  ap:
    ssid: "${friendly_name}"

captive_portal:
