substitutions:
  name: espcontrol-p4-86-ea56b4
  friendly_name: EspControl P4 4inch Square

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

packages:
  setup:
    url: https://github.com/jtenniswood/espcontrol/
    file: devices/esp32-p4-86/packages.yaml
    refresh: 1sec
