#!/usr/bin/env python3
"""Generate repeated ESPHome button-slot wiring from device_slots.json."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFS = ROOT / "scripts" / "device_slots.json"


def load_devices() -> list[dict]:
    with DEFS.open(encoding="utf-8") as f:
        data = json.load(f)
    return data["devices"]


def button_package_block(device: dict) -> str:
    lines = [
        "  # BEGIN GENERATED BUTTON PACKAGES",
        "  # Generated by scripts/generate_device_slots.py from scripts/device_slots.json.",
        f"  # Per-button entity/label/icon ({device['slots']} slots - {device['grid']} grid)",
    ]
    for num in range(1, device["slots"] + 1):
        key = f"  btn_{num}:".ljust(19)
        lines.append(
            f'{key}!include {{ file: ../../common/config/button_template.yaml, vars: {{ num: "{num}" }} }}'
        )
    lines.append("  # END GENERATED BUTTON PACKAGES")
    return "\n".join(lines) + "\n"


def replace_package_block(text: str, device: dict) -> str:
    block = button_package_block(device)
    marker = re.compile(
        r"(?ms)^  # BEGIN GENERATED BUTTON PACKAGES\n.*?^  # END GENERATED BUTTON PACKAGES\n"
    )
    if marker.search(text):
        return marker.sub(block, text, count=1)

    legacy = re.compile(
        r"(?ms)^  # Per-button entity/label/icon .*\n"
        r"(?:^  btn_\d+:\s+!include \{ file: ../../common/config/button_template.yaml, vars: \{ num: \"\d+\" \} \}\n)+"
    )
    next_text, count = legacy.subn(block, text, count=1)
    if count != 1:
        raise ValueError(f"Could not find button package block for {device['slug']}")
    return next_text


def button_slot_macro() -> str:
    return (
        "#define BTN_SLOT(n) { button_##n##_config, button_##n, button_##n##_icon_label, "
        "button_##n##_text_label, button_##n##_sensor_container, button_##n##_sensor_label, "
        "button_##n##_unit_label }"
    )


def macro_array(name: str, macro: str, slots: int, per_line: int = 4) -> list[str]:
    lines = [f"            esphome::text::Text *{name}[] = {{"]
    values = [f"{macro}({num})" for num in range(1, slots + 1)]
    for idx in range(0, len(values), per_line):
        chunk = ", ".join(values[idx : idx + per_line])
        lines.append(f"              {chunk},")
    lines.append("            };")
    return lines


def cfg_lines(device: dict) -> list[str]:
    lines = [
        "            GridConfig cfg = {};",
        f"            cfg.num_slots = {device['slots']};",
        f"            cfg.cols = {device['cols']};",
    ]
    if device["color_correction"]:
        lines.append("            cfg.color_correction = true;")
    if device["wrap_tall_labels"]:
        lines.append("            cfg.wrap_tall_labels = true;")
    lines.append(f"            cfg.icon_font = id({device['icon_font']})->get_lv_font();")
    lines.append(
        f"            cfg.climate_control_icon_font = id({device['climate_control_icon_font']})->get_lv_font();"
    )
    lines.append(f"            cfg.sp_sensor_font = id({device['sensor_font']})->get_lv_font();")
    lines.append(f"            cfg.climate_target_font = id({device['climate_target_font']})->get_lv_font();")
    lines.append(f"            cfg.forecast_font = id({device['forecast_font']})->get_lv_font();")
    lines.append(f"            cfg.forecast_unit_font = id({device['forecast_unit_font']})->get_lv_font();")
    lines.append("            cfg.temperature_unit = id(temperature_unit_select).current_option();")
    lines.append("            cfg.timezone = id(timezone_select).current_option();")
    lines.append("            cfg.developer_experimental_features = id(developer_experimental_features).state;")
    return lines


def phase1_block(device: dict) -> str:
    lines = [
        "            // BEGIN GENERATED PHASE 1 GRID WIRING",
        "            // Generated by scripts/generate_device_slots.py from scripts/device_slots.json.",
        f"            {button_slot_macro()}",
        "            BtnSlot slots[] = {",
    ]
    for num in range(1, device["slots"] + 1):
        lines.append(f"              BTN_SLOT({num}),")
    lines.extend(
        [
            "            };",
            "            #undef BTN_SLOT",
            *cfg_lines(device),
            "            // END GENERATED PHASE 1 GRID WIRING",
        ]
    )
    return "\n".join(lines)


def phase2_block(device: dict) -> str:
    lines = [
        "            // BEGIN GENERATED PHASE 2 GRID WIRING",
        "            // Generated by scripts/generate_device_slots.py from scripts/device_slots.json.",
        f"            {button_slot_macro()}",
        "            #define SP_CFG(n) subpage_##n##_config",
        "            #define SP_EXT(n) subpage_##n##_config_ext",
        "            #define SP_EXT2(n) subpage_##n##_config_ext_2",
        "            #define SP_EXT3(n) subpage_##n##_config_ext_3",
        "            BtnSlot slots[] = {",
    ]
    for num in range(1, device["slots"] + 1):
        lines.append(f"              BTN_SLOT({num}),")
    lines.append("            };")
    lines.extend(macro_array("sp_cfgs", "SP_CFG", device["slots"]))
    lines.extend(macro_array("sp_ext", "SP_EXT", device["slots"]))
    lines.extend(macro_array("sp_ext2", "SP_EXT2", device["slots"]))
    lines.extend(macro_array("sp_ext3", "SP_EXT3", device["slots"]))
    lines.extend(
        [
            "            #undef BTN_SLOT",
            "            #undef SP_CFG",
            "            #undef SP_EXT",
            "            #undef SP_EXT2",
            "            #undef SP_EXT3",
            *cfg_lines(device),
            "            // END GENERATED PHASE 2 GRID WIRING",
        ]
    )
    return "\n".join(lines)


def replace_phase(text: str, phase: int, block: str, call: str, slug: str) -> str:
    marker = re.compile(
        rf"(?ms)^            // BEGIN GENERATED PHASE {phase} GRID WIRING\n"
        rf".*?^            // END GENERATED PHASE {phase} GRID WIRING"
    )
    if marker.search(text):
        return marker.sub(block, text, count=1)

    legacy = re.compile(
        rf"(?ms)(        # Phase {phase}:.*?\n        - lambda: \|-\n)(.*?)(            {call}\()"
    )
    next_text, count = legacy.subn(lambda m: m.group(1) + block + "\n" + m.group(3), text, count=1)
    if count != 1:
        raise ValueError(f"Could not find phase {phase} wiring block for {slug}")
    return next_text


def replace_sensor_blocks(text: str, device: dict) -> str:
    text = replace_phase(text, 1, phase1_block(device), "grid_phase1", device["slug"])
    text = replace_phase(text, 2, phase2_block(device), "grid_phase2", device["slug"])
    return text


def update(path: Path, new_text: str, check: bool, changed: list[Path]) -> None:
    old_text = path.read_text(encoding="utf-8")
    if old_text == new_text:
        return
    changed.append(path)
    if not check:
        path.write_text(new_text, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated YAML is stale")
    args = parser.parse_args()

    changed: list[Path] = []
    for device in load_devices():
        slug = device["slug"]
        package_path = ROOT / "devices" / slug / "packages.yaml"
        sensor_path = ROOT / "devices" / slug / "device" / "sensors.yaml"

        package_text = package_path.read_text(encoding="utf-8")
        update(package_path, replace_package_block(package_text, device), args.check, changed)

        sensor_text = sensor_path.read_text(encoding="utf-8")
        update(sensor_path, replace_sensor_blocks(sensor_text, device), args.check, changed)

    if args.check and changed:
        for path in changed:
            print(f"Generated YAML is stale: {path.relative_to(ROOT)}", file=sys.stderr)
        return 1

    if changed:
        for path in changed:
            print(f"updated {path.relative_to(ROOT)}")
    else:
        print("Device slot YAML is up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
